# ==========================================
# DATABASE
# ==========================================
spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5432/banking_system}

# ==========================================
# SPRINGDOC / SWAGGER
# ==========================================
springdoc.api-docs.enabled=true
springdoc.swagger-ui.enabled=true