spring.application.name=banking-system

spring.datasource.url=jdbc:postgresql://localhost:5432/banking_system
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.open-in-view=false
spring.sql.init.mode=always

jwt.secret=${JWT_SECRET}

app.admin.username=${ADMIN_USERNAME:}
app.admin.email=${ADMIN_EMAIL:}
app.admin.password=${ADMIN_PASSWORD:}

# Address API
integration.address.viacep.base-url=https://viacep.com.br
integration.address.brasilapi.base-url=https://brasilapi.com.br

# LOGS
logging.level.com.lucas.bankingsystem=INFO

# SpringDoc / Swagger
# Controla a disponibilização da documentação OpenAPI
springdoc.api-docs.enabled=${SWAGGER_ENABLED:true}
# Controla a interface gráfica do Swagger
springdoc.swagger-ui.enabled=${SWAGGER_ENABLED:true}