-- ============================================================
-- Sequences
-- ============================================================

CREATE SEQUENCE account_number_seq
    START WITH 1
    INCREMENT BY 1;

-- ============================================================
-- Tables
-- ============================================================

CREATE TABLE addresses
(
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY,
    city          VARCHAR(100) NOT NULL,
    complement    VARCHAR(100),
    neighborhood  VARCHAR(100) NOT NULL,
    postal_code   VARCHAR(8)   NOT NULL,
    state         VARCHAR(2)   NOT NULL,
    street_name   VARCHAR(150) NOT NULL,
    street_number VARCHAR(10)  NOT NULL,

    CONSTRAINT addresses_pkey
        PRIMARY KEY (id),

    CONSTRAINT ck_addresses_state
        CHECK (
            state IN (
                      'AC', 'AL', 'AP', 'AM', 'BA', 'CE', 'DF',
                      'ES', 'GO', 'MA', 'MT', 'MS', 'MG', 'PA',
                      'PB', 'PR', 'PE', 'PI', 'RJ', 'RN', 'RS',
                      'RO', 'RR', 'SC', 'SP', 'SE', 'TO'
                )
            )
);

CREATE TABLE clients
(
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY,
    cpf          VARCHAR(11)  NOT NULL,
    email        VARCHAR(255) NOT NULL,
    name         VARCHAR(125) NOT NULL,
    phone_number VARCHAR(11)  NOT NULL,
    address_id   BIGINT       NOT NULL,

    CONSTRAINT clients_pkey
        PRIMARY KEY (id),

    CONSTRAINT uk_clients_cpf
        UNIQUE (cpf),

    CONSTRAINT uk_clients_email
        UNIQUE (email),

    CONSTRAINT uk_clients_address
        UNIQUE (address_id),

    CONSTRAINT fk_clients_address
        FOREIGN KEY (address_id)
            REFERENCES addresses (id)
);

CREATE TABLE accounts
(
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY,
    account_number VARCHAR(5)     NOT NULL,
    balance        NUMERIC(19, 2) NOT NULL,
    status         VARCHAR(20)    NOT NULL,
    account_type   VARCHAR(20)    NOT NULL,
    client_id      BIGINT         NOT NULL,
    account_digit  VARCHAR(1)     NOT NULL,

    CONSTRAINT accounts_pkey
        PRIMARY KEY (id),

    CONSTRAINT uk_accounts_account_number
        UNIQUE (account_number),

    CONSTRAINT ck_accounts_balance_non_negative
        CHECK (balance >= 0),

    CONSTRAINT ck_accounts_account_type
        CHECK (account_type IN ('CHECKING', 'SAVINGS')),

    CONSTRAINT ck_accounts_status
        CHECK (status IN ('ACTIVE', 'CANCELLED')),

    CONSTRAINT fk_accounts_client
        FOREIGN KEY (client_id)
            REFERENCES clients (id)
);

CREATE TABLE checking_accounts
(
    id BIGINT NOT NULL,

    CONSTRAINT checking_accounts_pkey
        PRIMARY KEY (id),

    CONSTRAINT fk_checking_accounts_account
        FOREIGN KEY (id)
            REFERENCES accounts (id)
);

CREATE TABLE savings_accounts
(
    id              BIGINT NOT NULL,
    last_yield_date DATE   NOT NULL,

    CONSTRAINT savings_accounts_pkey
        PRIMARY KEY (id),

    CONSTRAINT fk_savings_accounts_account
        FOREIGN KEY (id)
            REFERENCES accounts (id)
);

CREATE TABLE transactions
(
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY,
    amount           NUMERIC(19, 2) NOT NULL,
    created_at       TIMESTAMP(6)   NOT NULL,
    transaction_type VARCHAR(30)    NOT NULL,
    account_id       BIGINT         NOT NULL,
    transaction_code UUID           NOT NULL,

    CONSTRAINT transactions_pkey
        PRIMARY KEY (id),

    CONSTRAINT uk_transactions_code
        UNIQUE (transaction_code),

    CONSTRAINT ck_transactions_amount_positive
        CHECK (amount > 0),

    CONSTRAINT ck_transactions_transaction_type
        CHECK (
            transaction_type IN (
                                 'DEPOSIT',
                                 'WITHDRAWAL',
                                 'TRANSFER_SENT',
                                 'TRANSFER_RECEIVED',
                                 'YIELD'
                )
            ),

    CONSTRAINT fk_transactions_account
        FOREIGN KEY (account_id)
            REFERENCES accounts (id)
);

CREATE TABLE users
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY,
    username   VARCHAR(20)  NOT NULL,
    email      VARCHAR(255) NOT NULL,
    password   VARCHAR(255) NOT NULL,
    role       VARCHAR(20)  NOT NULL,
    active     BOOLEAN      NOT NULL,
    created_at TIMESTAMP(6) NOT NULL,
    updated_at TIMESTAMP(6) NOT NULL,

    CONSTRAINT users_pkey
        PRIMARY KEY (id),

    CONSTRAINT uk_users_username
        UNIQUE (username),

    CONSTRAINT uk_users_email
        UNIQUE (email),

    CONSTRAINT ck_users_role
        CHECK (role IN ('ADMIN', 'EMPLOYEE'))
);

-- ============================================================
-- Indexes
-- ============================================================

CREATE UNIQUE INDEX uk_accounts_client_type_active
    ON accounts (client_id, account_type)
    WHERE status = 'ACTIVE';

CREATE UNIQUE INDEX uk_transactions_daily_yield
    ON transactions (account_id, (created_at::date))
    WHERE transaction_type = 'YIELD';